### PR TITLE
updated add_file method to enable moving of files

### PR DESCRIPTION
**Pull request by rpinnaka**

### CODE REVIEW

**Comment by mattphotonman** [comment]
@rpinnaka I changed the `move_files` default to be `False` rather than `no_default`.

**Comment by rpinnaka** [comment]
okay @mattphotonman

**Comment by mattphotonman** [comment]
> okay @mattphotonman

@rpinnaka, please merge when ready.

**Comment by rpinnaka** [comment]
merged @mattphotonman, thanks.

**Pull request merged**
